package.json

Fixing import duties bug

---

Jenkinsfile

extending timeouts to 1 week for stages

---

Jenkinsfile

Fixing Jenkins pipeline
- setting timeout to 7 DAYS

Changing back to unit of DAYS

---

src/services/SheriffDutyService/SheriffDutyAssignmentMap.ts
src/services/SheriffDutyService/SheriffDutyAutoAssigner.ts
src/services/SheriffDutyService/index.ts

Bug jira ss10

---

database/liquibase/data/shersched.db.changelog.data.dev-court_role_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-courtroom.xml
database/liquibase/data/shersched.db.changelog.data.dev-escort_run.xml
database/liquibase/data/shersched.db.changelog.data.dev-gender_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-jail_role_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-leave_cancel_reason_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-leave_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-leave_sub_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-location.xml
database/liquibase/data/shersched.db.changelog.data.dev-other_assign_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-region.xml
database/liquibase/data/shersched.db.changelog.data.dev-sheriff.xml
database/liquibase/data/shersched.db.changelog.data.dev-sheriff_rank_code.xml
database/liquibase/data/shersched.db.changelog.data.dev-work_section_code.xml
database/liquibase/shersched.db.changelog.MASTER.xml

Added changelogs for data in dev environment

---

database/liquibase/data/shersched.db.changelog.data.prod-court_role_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-courtroom.xml
database/liquibase/data/shersched.db.changelog.data.prod-escort_run.xml
database/liquibase/data/shersched.db.changelog.data.prod-gender_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-jail_role_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-leave_cancel_reason_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-leave_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-leave_sub_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-location.xml
database/liquibase/data/shersched.db.changelog.data.prod-other_assign_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-region.xml
database/liquibase/data/shersched.db.changelog.data.prod-sheriff.xml
database/liquibase/data/shersched.db.changelog.data.prod-sheriff_rank_code.xml
database/liquibase/data/shersched.db.changelog.data.prod-work_section_code.xml

Added prod changelog

---

src/controllers/DutyController.ts
src/infrastructure/DatabaseService.ts
src/routes.ts
src/services/DutyService.ts
src/services/SheriffDutyService/SheriffDutyAssignmentMap.ts
src/services/SheriffDutyService/SheriffDutyAutoAssigner.ts

Added support to filter assignments by date and location

Fixes the auto assignment to set the sheriff that best matches the duty

---

dist/client/Client.d.ts
package.json
src/client/Client.ts

Fixed api client typing file.

---

dist/client/Client.d.ts
package.json
src/client/Client.ts

This reverts commit 569bc01c15ad37cbfb8539a39528f40fe9da15b8.

Revert "Fixed api client typing file."

---

src/services/SheriffDutyService/SheriffDutyAutoAssigner.ts

Fixed auto assignment shifts filter using inclusive date

---

src/infrastructure/ExpirableDatabaseService.ts
src/models/Assignment.ts
src/services/AssignmentService.ts

Added ability to specify the effective/expiry date of the assignments

---

src/services/SheriffDutyService/SheriffDutyAutoAssigner.ts

Fixed auto assign not working for exact match

---

database/liquibase/data/shersched.db.changelog.data.dev-escort_run_add_assignments.xml
database/liquibase/shersched.db.changelog.MASTER.xml
database/migrate-db.sh

Add escort assignments and uncomment liquibase script

---

docker/README.md

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

Update docker environment database restore documentation

---

docker/README.md
docker/manage

- Automates the process or resetting the API's database and restoring from backup.
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

Add restore command for docker environment

---

docker/manage

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

Add help documentation for the restore command

---

src/services/SheriffService.ts

Clean up sheriff current location implementation.

---

src/services/SheriffService.ts

Fix bug with loaned sheriff's query in SheriffService getAll.

---

src/infrastructure/ExpirableDatabaseService.ts
src/services/SheriffLocationService.ts

More changes for sheriff locations.

---

src/infrastructure/ExpirableDatabaseService.ts
src/models/SheriffLocation.ts
src/services/EffectiveSheriffLocationService.ts
src/services/SheriffLocationService.ts
src/services/SheriffService.ts

Fix regression in SheriffService and SheriffLocationService, and add new abstract EffectiveSheriffLocationService.

Fix regression in SheriffService and SheriffLocationService.

---

database/liquibase/structure/shersched.db.changelog.migrate-v1-v2.xml
database/liquibase/structure/v2-authorization/shersched.db.changelog.authorization.table-auth_api_scope.xml
database/liquibase/structure/v2-authorization/shersched.db.changelog.authorization.table-auth_frontend_scope.xml
database/liquibase/structure/v2-authorization/shersched.db.changelog.authorization.table-auth_role_permission.xml

Fix Liquibase v1 -> v2 migration script bugs.

---

database/migrade-db.local.sh
docker/docker-compose.yml

Tweak migrate-db for dev.

---

database/liquibase/shersched.db.changelog.env-schemas_roles_extensions.xml

Comment out reassign / drop POSTGRES_APP_USER stuff.

---

database/liquibase/structure/v1-v2-migration-temp-tables/shersched.db.changelog.temp-table-assignment.xml

Fix bug in temp-table-assignment script.

---

database/liquibase/structure/v2-assign-types/shersched.db.changelog.assign-types.table-assignment.xml

Fix constraint.

---

database/liquibase/structure/shersched.db.changelog.migrate-v1-v2.restore-data.xml

Change restore data script order.

---

database/liquibase/structure/shersched.db.changelog.migrate-v1-v2.restore-data.xml

Fix uuids in restore data script.

---

openshift/api-postgres-deploy.json

Log execNewPod command script.

---

openshift/api-postgress-deploy-bluegreen.json
openshift/test/api-postgress-ephemeral.json

Log all execNewPod command scripts.

---

database/liquibase/structure/shersched.db.changelog.migrate-v1-v2.xml
database/migrate-db.sh

Add sort_order column to leave_sub_code in Liquibase migration.

---

src/services/AssignmentService.ts

Code columns were removed as part of migration (replaced with UUIDs).

Remove old code columns from field map in AssignmentService.

---

src/infrastructure/DatabaseService.ts

Add trace to DatabaseService to help catch any query errors.

---

database/liquibase/shersched.db.changelog.env-schemas_roles_extensions.xml

Only create POSTGRES_APP_USER if the user doesn't exist.

---

database/liquibase/shersched.db.changelog.env-schemas_roles_extensions.xml

Fix user create query.

---

database/liquibase/shersched.db.changelog.env-schemas_roles_extensions.xml

Use createProcedure instead of sql for creating user.

---

database/liquibase/shersched.db.changelog.env-schemas_roles_extensions.xml
package.json

Add extensions schema and install uuid in db_env_02_app_user script.
